### ISSUE TITLE
Problem with the new URL

### ISSUE THREAD

**Issue by thorildor** [piratebayproxy/UnblockedPiratebayClean#11]
Hello,

TPB(thepiratebay.org) has changed URL and it seems to do not work anymore. Design and image doesn't appeard(just like this issue https://github.com/piratebayproxy/UnblockedPiratebayClean/issues/6 ), it seems to trying to directly connect to thepiratebay.org, so it does not work on countries where TPB is blocked.(I tried to change the URL on config but do not work).
Thanks(sorry for my english)

**Comment by piratebayproxy** [comment]
Fixed by updated the URL in config.php and functions.php

**Comment by thorildor** [comment]
Thanks
