### ISSUE TITLE
HTTP ERROR 500 on everything

### ISSUE THREAD

**Issue by FGOD1983** [piratebayproxy/UnblockedPiratebayClean#15]
Hey, I was trying to setup a Pirate Bay Proxy but for some reason it loads the main page, but everything I do ends up with a HTTP ERROR 500. 

I am running this on a Ubuntu 16.04 server which runs Nginx 1.10.3

I also tried the Nginx setup too, but that is saying that the conf file is not good (subs_filter problems).

**Comment by piratebayproxy** [comment]
Check your nginx error log and see what's causing the 500 error.

With the nginx setup, did you compile your own version of nginx or use the one installed by the ubuntu package manager? (e.g. apt-get install nginx).  You have to compile nginx yourself in order to get the subs_filter module to work since it's not included in the nginx from the ubuntu repositories.

**Comment by FGOD1983** [comment]
hmm you might be right on this. I installed it through the Ubuntu package manager, but I'll try again with the compiled version on my VPS instead of my Webserver. Thx for the feedback. I'll let you know if it worked.

**Comment by FGOD1983** [comment]
oke, it worked with the Nginx setup from the guide on a fresh install of Ubuntu on my VPS, but the guide is full of errors.

for starters, "wget http://nginx.org/download/nginx-nginx-1.10.3.tar.gz" didn't work because the url is faulty. The link should only have one nginx- in it instead of 2. Then again, this version couldn't compile so I used the last version of nginx so far (nginx-1.13.8.tar.gz) which did compile with the subs_filters.

The extracting part has the same problem with one too many nginx- in the name.

and the command at the end to start nginx again when the conf is made is also faulty. This is "./usr/local/nginx/sbin/nginx" and should be "sudo /usr/local/nginx/sbin/nginx" (unless you are logged in as root)

Thx for the help!

**Comment by piratebayproxy** [comment]
Thanks for letting us know about the errors. We have fixed the commands and updated the guide a little. If you find any other issues, let us know.

**Comment by FGOD1983** [comment]
no problem :)
