### ISSUE TITLE
Search tool needs to be more for forgiving

### ISSUE THREAD

**Issue by 805bluebell** [piratebayproxy/UnblockedPiratebayClean#17]
Search doesn't help a user unless they have the exact title & they know its spelling well.
For eg:- Try "manmarziya"
No results with search.php
Google it & it will suggest you the correct spelling & give you all those results as well.
So, Just adding "n" at the end to make "manmarziyan"
And a lot of results pop up which is a nice UX.

Search needs an overhaul since all major websites have grown smart. Piratebay also should keep up the pace.

**Comment by piratebayproxy** [comment]
Any suggestions for improving TPB can be submitted on their forum here: https://pirates-forum.org/
Cheers
