### ISSUE TITLE
[Q] ES Modules

### ISSUE THREAD

**Issue by TriMoon** [piratebayproxy/UnblockedPiratebayClean#20]
Do you have any plans on converting the Javascripts to [ES-Modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules)?
Also get rid of the `document.write`, and raw html returned by functions :wink:

**Comment by piratebayproxy** [comment]
No, I don't really know how that would help a simple PHP script like this. To make it function you just upload the files to a web server.
The Javascript code is from TPB's site, we just modify it enough to make it work with the proxy.
