### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by johndoyle-cloudhigh** [piratebayproxy/UnblockedPiratebayClean#25]
Hello

Fresh install as I lost my old one.  I am just getting json with an empty results page

Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at make_search (main.js:23)
    at print_search (main.js:41)
    at search.php?q=first&all=on&search=Pirate+Search&page=0&orderby=:19

Any thoughts?

**Comment by erikewp** [comment]
I did a fresh install of the script and it worked on my end.

The error seems to indicate that the JSON file is not being retrieved from apibay.org. Is the curl support enabled in your PHP?

You can check this by creating a test.php file, adding <?php phpinfo(); ?> and then opening the file through your web browser. More details here: [https://tecadmin.net/create-phpinfo-file/](https://tecadmin.net/create-phpinfo-file/)
