### ISSUE TITLE
Search within the category not working

### ISSUE THREAD

**Issue by sizzlingkenny** [piratebayproxy/UnblockedPiratebayClean#26]
Search by Category is only working on 
https://pirateproxy.ltda/

![Screenshot](https://user-images.githubusercontent.com/53451293/116296208-5f03c800-a7b3-11eb-9b49-642d6d81bba9.png)

but its not working on my domain 

![Screenshot 2](https://user-images.githubusercontent.com/53451293/116296417-a427fa00-a7b3-11eb-8392-e70efb4e9d21.png)

why its only working on your site and not others? did you miss some coding in the files you offering here for others or there is some special way to enable this feature?

**Comment by piratebayproxy** [comment]
Looks like a bug in api.php. It seems that only first GET parameter is being used.

**Comment by piratebayproxy** [comment]
We replaced `$_GET['url']` with `$_SERVER['REQUEST_URI']` to capture all GET parameters. This fixed the issue.

pirateproxy.ltda uses NGINX proxy method (not PHP script) so that's why results were different.

**Comment by sizzlingkenny** [comment]
thanks a lot.. long live piratebayproxy...
