### ISSUE TITLE
Belgium

### ISSUE THREAD

**Issue by olafdv** [piratebayproxy/UnblockedPiratebayClean#5]
For blocking ads, what's the fastest route to a 404? localhost? 
Also, bitsnoop.com is blocked here so I took that bit out. But, i can't replace the width and height of the image. Weirdness.

	$page = str_replace("width=\"148\"","width=\"0\"", $page);

Works fine on an iframe but not on an image. Attribute is hard coded html in both cases. Any clues?

Sorry, just trying to get it clean-clean.

**Comment by piratebayproxy** [comment]
You would need to use regular expressions instead.
For example, to remove all the iframe ads, you can add: 
`$page = preg_replace('/<iframe.*iframe>/','',$page);`

**Comment by olafdv** [comment]
Ah, I got something to do then. :) Thanks for pointing me in the right direction. Again.

**Comment by olafdv** [comment]
By the way, is it correct loadurl doesn't function with external URL's? (Bittorrent link, etc)

**Comment by piratebayproxy** [comment]
The script is only for thepiratebay and will not work with other links or sites.
