### ISSUE TITLE
Problem, design and image doesn't appeard

### ISSUE THREAD

**Issue by thorildor** [piratebayproxy/UnblockedPiratebayClean#6]
Hello,(sorry for my english)

On blocked country, since the new TPB URL it seems that the images and the design don't appeard https://pirateproxy.sx/blog
it seems that the proxy try to connect directly to piratebay.org, which is blocked, which is probably the origin of the problem.

Thanks!

**Comment by piratebayproxy** [comment]
Thanks, I've added a fix

**Comment by thorildor** [comment]
Hello,  
Same problem, it seems to load directly from thepiratebay.la , so design, images don,'t appeared (example: http://tpb.proxyduck.org/?load=/top/400 ) on blocked country.

Thanks. (sorry for my englishà

**Comment by piratebayproxy** [comment]
I added a fix

**Comment by thorildor** [comment]
Thanks you're really quick ;). 
And not a issue but a question, is it possible to change the footer links (Proxy List | About | Blog
Usage policy | TOR | Promo | Doodles | Tag Cloud | Forum | PirateBrowser)?

Thanks

**Comment by piratebayproxy** [comment]
Yes, by using the str_replace function in includes/functions.php

If you look at lines 13, 14 and 15 in functions.php, you can see some examples.
