### ISSUE TITLE
TPB ads not working

### ISSUE THREAD

**Issue by thorildor** [piratebayproxy/UnblockedPiratebayClean#7]
Hello,

As you can see here: https://tpb.proxyduck.net/?load=/torrent/13226957/Biodrone_Battle_v1.1.1 it's like the TPB ads are not working(not found, not found).

Thanks

**Comment by piratebayproxy** [comment]
I've fixed the issue with the ads.  Some ads will load through the script, while other ones have been removed using regex.  Also, the CSS file at /static/css/pirate6.css has been updated.  So I recommend updating it on your end as well.

**Comment by thorildor** [comment]
Thankis for the fix ;).

And a new problem: the "stream it" new function is not working.

**Comment by piratebayproxy** [comment]
It seems to be working for me, can you confirm?
