### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by 6523x** [piratebayproxy/UnblockedPiratebayClean#8]
1. Finding this 404 in my logs: /static/img/icons/icon-tt.png, guess it has something to do with their new 'torrent time' function? Maybe add icon-tt.png to the master? 
2. Not all ads get canned with the current functions.php
3. Some caching can really speed up your proxy. Just a tip. ;)

**Comment by piratebayproxy** [comment]
I added the icons-tt.png file to the master branch.  The functions.php file has been updated with a new patch
